<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8XxMNv\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8XxMNv/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerX8XxMNv.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerX8XxMNv\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerX8XxMNv\appAppKernelProdContainer([
    'container.build_hash' => 'X8XxMNv',
    'container.build_id' => '35dc8102',
    'container.build_time' => 1778227977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8XxMNv');
